# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-ScriptTemplate
version:      0.08
version_from: ScriptTemplate.pm
installdirs:  site
requires:
    Carp:                          0
    FileHandle:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
